services:
    Akeneo\Connectivity\Connection\Infrastructure\Apps\EventSubscriber\AccessDeniedForRevokedAppTokenEventSubscriber:
        arguments:
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Persistence\IsAccessTokenRevokedQuery'
        autoconfigure: true

    Akeneo\Connectivity\Connection\Infrastructure\Apps\EventSubscriber\GroupAllIsRemovedFromUsersUsedByAppsOnUpdateEventSubscriber:
        autoconfigure: true
