services:
    Akeneo\Connectivity\Connection\Infrastructure\Apps\Install\InstallSubscriber:
        arguments:
            - '@database_connection'
            - '@Akeneo\Connectivity\Connection\Infrastructure\Apps\Install\AddAclToRoles'
        autoconfigure: true

    Akeneo\Connectivity\Connection\Infrastructure\Apps\Install\AddAclToRoles:
        arguments:
            - '@oro_security.acl.manager'
            - '@pim_user.repository.role'
