services:
  Akeneo\Platform\Installer\Infrastructure\EventSubscriber\MaintenanceModeSubscriber:
    arguments:
      - '@router'
      - '@Akeneo\Platform\Installer\Application\IsMaintenanceModeEnabled\IsMaintenanceModeEnabledHandler'
      - '@Akeneo\Platform\Installer\Application\UpdateMaintenanceMode\UpdateMaintenanceModeHandler'
    autoconfigure: true

  Akeneo\Platform\Installer\Infrastructure\Event\Subscriber\CreateNotMappedTablesSubscriber:
    arguments:
      - '@database_connection'
    autoconfigure: true

  Akeneo\Platform\Installer\Infrastructure\Event\Subscriber\MarkZddMigrationsAsMigratedSubscriber:
    arguments:
      - '@database_connection'
      - '@Akeneo\Tool\Component\StorageUtils\Database\SqlPlatformHelperInterface'
      - !tagged_iterator { tag: 'akeneo.pim.zdd_migration' }
    autoconfigure: true

  Akeneo\Platform\Installer\Infrastructure\Event\Subscriber\UpdateLastResetDateSubscriber:
    arguments:
      - '@Akeneo\Platform\Installer\Infrastructure\Persistence\Sql\SaveResetEvent'
    autoconfigure: true
