/**
 * Jest config for Stryker mutation testing.
 *
 * Extends unit.jest.js with three categories of overrides required for the
 * Stryker sandbox environment:
 *
 * 1. moduleNameMapper: redirects every entry that points into public/ (which
 *    Stryker excludes via ignorePatterns) to the corresponding TypeScript/JS
 *    source in src/, or to a minimal stub for generated JSON files that have
 *    no source equivalent. Also adds workspace-specific aliases (@src/ for
 *    Connectivity Connection).
 *
 * 2. testPathIgnorePatterns: selectively removes workspace exclusions from
 *    unit.jest.js. Connectivity and identifier-generator (co-located only)
 *    tests are included. Category tests are excluded because they use
 *    jest.spyOn(global, 'fetch') which conflicts with jest-fetch-mock.
 *    CommunicationChannelBundle remains excluded (gitignored schema.json).
 *
 * 3. testMatch: extended to cover Connectivity (.test.ts in tests/) and
 *    identifier-generator (.test.ts co-located) in addition to root .unit.ts.
 */
const path = require('path');
const unitConfig = require('./unit.jest.js');

const PIMUI_SRC = '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/Resources/public';
const CONNECTIVITY_FRONT = '<rootDir>/src/Akeneo/Connectivity/Connection/front';
const MEASURE_FRONT = '<rootDir>/src/Akeneo/Tool/Bundle/MeasureBundle/front';
const SETTINGS_UI_FRONT = '<rootDir>/src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui';
const ACTIVITY_WORKSPACE = '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity';
const LEGACY_BRIDGE_WORKSPACE = '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge';
const ENRICHMENT_WORKSPACE = '<rootDir>/src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment';
const IMPORT_EXPORT_FRONT = '<rootDir>/src/Akeneo/Platform/Bundle/ImportExportBundle/front';
const CATALOG_VOLUME_FRONT = '<rootDir>/src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front';

module.exports = {
  ...unitConfig,
  // unit.jest.js sets rootDir = process.env.INIT_CWD || path.resolve(...).
  // INIT_CWD is set by yarn to the original project root. When Stryker copies
  // the project into a sandbox (/tmp/stryker-tmp/sandbox-XXX/) and mutates files
  // there, INIT_CWD still points to the original project. Jest then runs tests
  // against the ORIGINAL (unmutated) code → all mutants survive.
  // Fix: always resolve rootDir relative to __dirname (which IS the sandbox copy).
  rootDir: path.resolve(__dirname, '../../../..'),
  // On CI self-hosted runners /tmp is shared with sticky bit, so a prior run's
  // /tmp/jest may be owned by a different UID. Use RUNNER_TEMP (per-job unique).
  cacheDirectory: process.env.RUNNER_TEMP ? `${process.env.RUNNER_TEMP}/jest-cache` : unitConfig.cacheDirectory,
  moduleNameMapper: {
    ...unitConfig.moduleNameMapper,
    // pim/* aliases point to public/bundles/pimui which is excluded from the
    // Stryker sandbox. Redirect to the TypeScript/JS sources directly.
    'pim/fetcher-registry': `${PIMUI_SRC}/js/fetcher/fetcher-registry.js`,
    'pim/router': `${PIMUI_SRC}/js/router.js`,
    routing: `${PIMUI_SRC}/js/fos-routing-wrapper.js`,
    // fos_js_routes.json is gitignored (generated by Symfony). Use an empty stub.
    routes: `${__dirname}/stubs/routes.stub.json`,
    // module-registry.js is gitignored (generated during front build). Use an empty stub.
    '^module-registry$': `${__dirname}/stubs/module-registry.stub.js`,
    // Connectivity Connection workspace: @src/ → front/src/
    '^@src/(.*)$': `${CONNECTIVITY_FRONT}/src/$1`,
    // Yarn workspace symlinks may break in the Stryker sandbox — resolve directly.
    // Point to src/ (not lib/) because lib/ is compiled and may not exist on CI.
    '^@akeneo-pim-community/catalogs$': '<rootDir>/components/catalogs/mock/src/exports.ts',
    // settings-ui workspace: path imports include /src/ prefix already.
    '^@akeneo-pim-community/settings-ui/(.*)$': `${SETTINGS_UI_FRONT}/$1`,
    '^@akeneo-pim-community/settings-ui$': `${SETTINGS_UI_FRONT}/src/index.ts`,
    // Activity workspace dependencies: direct resolution to avoid sandbox symlink issues.
    // Deep path imports (e.g. legacy-bridge/tests/front/unit/utils) need explicit mapping.
    '^@akeneo-pim-community/legacy-bridge/(.*)$': `${LEGACY_BRIDGE_WORKSPACE}/$1`,
    '^@akeneo-pim-community/enrichment$': `${ENRICHMENT_WORKSPACE}/src/index.ts`,
    '^@akeneo-pim-community/enrichment/(.*)$': `${ENRICHMENT_WORKSPACE}/$1`,
  },
  // Explicit testMatch targeting ONLY modules in the Stryker mutate scope.
  // unit.jest.js uses '<rootDir>/src/**/*.unit.(ts|tsx)' which is too broad —
  // it pulls in UIBundle (pim/form-builder), OroBundle (DataGrid), UserManagement
  // etc. that depend on legacy Backbone modules not available in the sandbox.
  testMatch: [
    // DataQualityInsights — only reducer, fetcher, helper, domain tests.
    // Component tests (Application/component/, Dashboard/, ProductEvaluationTab/)
    // use @akeneo-pim-community/data-quality-insights via workspace symlinks
    // that break in the Stryker sandbox (mock paths resolve to original project).
    '<rootDir>/src/Akeneo/Pim/Automation/DataQualityInsights/**/infrastructure/**/*.unit.(ts|tsx)',
    '<rootDir>/src/Akeneo/Pim/Automation/DataQualityInsights/**/Application/helper/**/*.unit.(ts|tsx)',
    '<rootDir>/src/Akeneo/Pim/Automation/DataQualityInsights/**/Domain/**/*.unit.(ts|tsx)',
    // Connectivity (dedicated tests/ directory with .test.ts pattern)
    `${CONNECTIVITY_FRONT}/tests/**/*.test.(ts|tsx)`,
    // MeasureBundle (co-located .test.ts)
    `${MEASURE_FRONT}/src/**/*.test.(ts|tsx)`,
    // UserManagement/tools: no Backbone dependencies, safe in sandbox.
    '<rootDir>/src/Akeneo/UserManagement/Bundle/Resources/public/js/tools/*.unit.ts',
    // settings-ui infrastructure: fetchers/removers only — no Backbone or workspace symlinks.
    '<rootDir>/src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/infrastructure/**/*.unit.ts',
    // Activity workspace — pure data transformation and hook tests, no Backbone.
    // Tests run under Bun in the main CI step but are Jest-compatible for Stryker.
    `${ACTIVITY_WORKSPACE}/**/*.unit.ts`,
    // NOTE: the Import-Export workspace (migrated to the Bun runner in #205) is
    // intentionally NOT matched here. Its tests mock @akeneo-pim-community/shared
    // with `{...require('@akeneo-pim-community/shared')}` INSIDE the jest.mock
    // factory of that same module — valid under Bun, but an infinite recursion
    // ("Maximum call stack size exceeded") under Stryker's jest-runtime dry run.
    // They crash the runner rather than provide coverage, so excluding them is
    // coverage-neutral; mutating import-export source needs a dedicated Bun-based
    // Stryker config, like the other Bun workspaces.
    // Catalog-Volume-Monitoring workspace — volume fetchers, hooks and components.
    `${CATALOG_VOLUME_FRONT}/src/**/*.test.(ts|tsx)`,
    // Identifier Generator, CatalogVolumeMonitoring, and Process Tracker have
    // their own jest configs with incompatible settings (setupFiles, tsconfig,
    // resetMocks). They use dedicated Stryker configs (stryker-*.config.json).
    // DataGrid React components — pure React, no Backbone in test deps, safe in sandbox.
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/DisplaySelector.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/display-selector.unit.tsx',
    // DataGrid React cells (C1 wave 2) — Backgrid StringCell base mocked at test level.
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/EnabledBadge.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/react-cell-base.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/enabled-cell.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/CompletenessBadge.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/completeness-cell.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/complete-variant-product-cell.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/ProductImage.unit.tsx',
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/product-and-product-model-image-cell.unit.tsx',
    // DataGrid pagination (C1 wave 3) — presentational bar, pure React, no Backbone in test deps.
    '<rootDir>/src/Oro/Bundle/PimDataGridBundle/tests/front/unit/PaginationBar.unit.tsx',
    // UIBundle product/grid — locale-switcher: Backbone view mocked at test level.
    '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/grid/locale-switcher.unit.tsx',
    // View-selector leaf pieces (C1 Slice A) — pure presentational React, no Backbone in test deps.
    '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/grid/ViewSelectorLine.unit.tsx',
    '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/grid/ViewSelectorCurrent.unit.tsx',
    // View-selector CRUD pieces (C1 Slice B) — pure presentational React, no Backbone in test deps.
    '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/grid/ViewSelectorActionLink.unit.tsx',
    '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/grid/CreateViewFields.unit.tsx',
  ],
  // public/bundles/ does not exist in the sandbox; akeneopimstructure/ and pimui/
  // are already handled by moduleNameMapper above and in unit.jest.js.
  moduleDirectories: ['node_modules'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/front-packages/',
    '<rootDir>/vendors/',
    // Category and CatalogVolumeMonitoring tests use jest.spyOn(global, 'fetch')
    // which conflicts with the jest-fetch-mock setup from the root config.
    '<rootDir>/src/Akeneo/Category/',
    '<rootDir>/src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/',
    // models/*.schema.json files are gitignored (generated by yarn generate-models).
    '<rootDir>/src/Akeneo/Platform/Bundle/CommunicationChannelBundle/',
    // identifier-generator uses its own Stryker config (stryker-identifier-generator.config.json).
    '<rootDir>/components/identifier-generator/',
    // Import-Export is a Bun workspace whose mocks recurse under jest (see the
    // testMatch note above) — keep its tests out of the jest-runtime dry run.
    `${IMPORT_EXPORT_FRONT}/`,
  ],
  setupFiles: [
    `${__dirname}/mocks.js`,
    // Use Stryker-safe fetch mock that suppresses JSDOM teardown errors without
    // calling process.exit() (which kills the Stryker child worker).
    `${__dirname}/strykerFetchMock.ts`,
    // Connectivity workspace fetch mock (same contract as root fetchMock.ts)
    `${CONNECTIVITY_FRONT}/tests/mocks/fetch-mock.ts`,
  ],
};
