/**
 * Jest config for Stryker mutation testing.
 *
 * Extends unit.jest.js with three categories of overrides required for the
 * Stryker sandbox environment:
 *
 * 1. moduleNameMapper: redirects every entry that points into public/ (which
 *    Stryker excludes via ignorePatterns) to the corresponding TypeScript/JS
 *    source in src/, or to a minimal stub for generated JSON files that have
 *    no source equivalent. Also adds workspace-specific aliases (@src/ for
 *    Connectivity Connection).
 *
 * 2. testPathIgnorePatterns: selectively removes workspace exclusions from
 *    unit.jest.js. Connectivity and identifier-generator (co-located only)
 *    tests are included. Category tests are excluded because they use
 *    jest.spyOn(global, 'fetch') which conflicts with jest-fetch-mock.
 *    CommunicationChannelBundle remains excluded (gitignored schema.json).
 *
 * 3. testMatch: extended to cover Connectivity (.test.ts in tests/) and
 *    identifier-generator (.test.ts co-located) in addition to root .unit.ts.
 */
const path = require('path');
const unitConfig = require('./unit.jest.js');

const PIMUI_SRC = '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/Resources/public';
const CONNECTIVITY_FRONT = '<rootDir>/src/Akeneo/Connectivity/Connection/front';
const IDENTIFIER_GEN_FRONT = '<rootDir>/components/identifier-generator/front';

module.exports = {
  ...unitConfig,
  // On CI self-hosted runners /tmp is shared with sticky bit, so a prior run's
  // /tmp/jest may be owned by a different UID. Use RUNNER_TEMP (per-job unique).
  cacheDirectory: process.env.RUNNER_TEMP ? `${process.env.RUNNER_TEMP}/jest-cache` : unitConfig.cacheDirectory,
  moduleNameMapper: {
    ...unitConfig.moduleNameMapper,
    // pim/* aliases point to public/bundles/pimui which is excluded from the
    // Stryker sandbox. Redirect to the TypeScript/JS sources directly.
    'pim/fetcher-registry': `${PIMUI_SRC}/js/fetcher/fetcher-registry.js`,
    'pim/router': `${PIMUI_SRC}/js/router.js`,
    routing: `${PIMUI_SRC}/js/fos-routing-wrapper.js`,
    // fos_js_routes.json is gitignored (generated by Symfony). Use an empty stub.
    routes: `${__dirname}/stubs/routes.stub.json`,
    // module-registry.js is gitignored (generated during front build). Use an empty stub.
    '^module-registry$': `${__dirname}/stubs/module-registry.stub.js`,
    // Connectivity Connection workspace: @src/ → front/src/
    '^@src/(.*)$': `${CONNECTIVITY_FRONT}/src/$1`,
  },
  testMatch: [
    ...unitConfig.testMatch,
    // Connectivity tests live in tests/ with .test.(ts|tsx) pattern
    `${CONNECTIVITY_FRONT}/tests/**/*.test.(ts|tsx)`,
    // identifier-generator co-located tests (not in __tests__/ dirs)
    `${IDENTIFIER_GEN_FRONT}/src/**/*.test.(ts|tsx)`,
    `${IDENTIFIER_GEN_FRONT}/src/**/*.unit.(ts|tsx)`,
  ],
  // public/bundles/ does not exist in the sandbox; akeneopimstructure/ and pimui/
  // are already handled by moduleNameMapper above and in unit.jest.js.
  moduleDirectories: ['node_modules'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/front-packages/',
    '<rootDir>/vendors/',
    // Category tests use jest.spyOn(global, 'fetch') which conflicts with
    // the jest-fetch-mock setup from the root config.
    '<rootDir>/src/Akeneo/Category/',
    // models/*.schema.json files are gitignored (generated by yarn generate-models).
    '<rootDir>/src/Akeneo/Platform/Bundle/CommunicationChannelBundle/',
    // identifier-generator __tests__/ suites use workspace-specific providers
    // (Router, DependenciesContext) not available in the root Jest config.
    // Only co-located *.test.ts files (not in __tests__/ dirs) are included.
    '/components/identifier-generator/front/src/.*/__tests__/',
  ],
  setupFiles: [
    ...unitConfig.setupFiles,
    // Connectivity workspace fetch mock (same contract as root fetchMock.ts)
    `${CONNECTIVITY_FRONT}/tests/mocks/fetch-mock.ts`,
  ],
};
