/**
 * Jest config for Stryker mutation testing.
 *
 * Extends unit.jest.js with two categories of overrides required for the
 * Stryker sandbox environment:
 *
 * 1. moduleNameMapper: redirects every entry that points into public/ (which
 *    Stryker excludes via ignorePatterns) to the corresponding TypeScript/JS
 *    source in src/, or to a minimal stub for generated JSON files that have
 *    no source equivalent.
 *
 * 2. testPathIgnorePatterns: excludes test suites whose transitive imports
 *    require gitignored generated files that Stryker cannot copy to the sandbox
 *    (e.g. CommunicationChannelBundle models/*.schema.json).
 */
const path = require('path');
const unitConfig = require('./unit.jest.js');

const PIMUI_SRC = '<rootDir>/src/Akeneo/Platform/Bundle/UIBundle/Resources/public';

module.exports = {
  ...unitConfig,
  moduleNameMapper: {
    ...unitConfig.moduleNameMapper,
    // pim/* aliases point to public/bundles/pimui which is excluded from the
    // Stryker sandbox. Redirect to the TypeScript/JS sources directly.
    'pim/fetcher-registry': `${PIMUI_SRC}/js/fetcher/fetcher-registry.js`,
    'pim/router': `${PIMUI_SRC}/js/router.js`,
    routing: `${PIMUI_SRC}/js/fos-routing-wrapper.js`,
    // fos_js_routes.json is gitignored (generated by Symfony). Use an empty stub.
    routes: `${__dirname}/stubs/routes.stub.json`,
    // module-registry.js is gitignored (generated during front build). Use an empty stub.
    '^module-registry$': `${__dirname}/stubs/module-registry.stub.js`,
  },
  // public/bundles/ does not exist in the sandbox; akeneopimstructure/ and pimui/
  // are already handled by moduleNameMapper above and in unit.jest.js.
  moduleDirectories: ['node_modules'],
  testPathIgnorePatterns: [
    ...unitConfig.testPathIgnorePatterns,
    // models/*.schema.json files are gitignored (generated by yarn generate-models).
    '<rootDir>/src/Akeneo/Platform/Bundle/CommunicationChannelBundle/',
  ],
};
